### ISSUE TITLE
NoMethodError: undefined method `scope_for_create' for {}:ActiveSupport::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by afn** [huacnlee/rails-settings-cached#37]
I get this error when I use rails-settings-cached 0.3.2 with Rails 4.1.

The root cause is that Settings.all returns an instance of ActiveSupport::HashWithIndifferentAccess rather than ActiveRecord::Relation, and Rails now expects .all to return a relation.

Here's a backtrace:

```
     NoMethodError:
       undefined method `scope_for_create' for {}:ActiveSupport::HashWithIndifferentAccess
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0.beta1/lib/active_record/scoping/named.rb:39:in `scope_attributes'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0.beta1/lib/active_record/scoping.rb:25:in `populate_with_current_scope_attributes'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0.beta1/lib/active_record/core.rb:177:in `initialize'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0.beta1/lib/active_record/inheritance.rb:27:in `new'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0.beta1/lib/active_record/inheritance.rb:27:in `new'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0.beta1/lib/active_record/relation.rb:108:in `block in new'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0.beta1/lib/active_record/relation.rb:285:in `scoping'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0.beta1/lib/active_record/relation.rb:108:in `new'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/rails-settings-cached-0.3.2/lib/rails-settings/settings.rb:79:in `[]='
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/rails-settings-cached-0.3.2/lib/rails-settings/settings.rb:25:in `rescue in method_missing'
     # /Users/afn/.rvm/gems/ruby-2.1.0/gems/rails-settings-cached-0.3.2/lib/rails-settings/settings.rb:18:in `method_missing'
```

For now I've worked around it by monkey-patching HashWithIndifferent access thusly, but clearly this isn't the right approach:

```
module ActiveSupport
  class HashWithIndifferentAccess
    def scope_for_create
      {}
    end
  end
end
```

I think the proper solution is to change the definition of self.all to return something that more closely resembles an ActiveRecord relation.

**Comment by adibsaad** [comment]
Still getting this issue on Rails 4.2.1, using version 0.3.1 as per the readme.

When I apply the monkey patch shown by @afn, I get the error shown in #45.

Currently don't have a workaround.

**Comment by huacnlee** [comment]
@adibsaad use 0.4.1

**Comment by adibsaad** [comment]
@huacnlee If i use 0.4.1 with Rails 4.2.1, I just get the error shown in #45
