### ISSUE TITLE
use mysql 0.4 problem

### ISSUE THREAD

**Issue by kingwkb** [huacnlee/rails-settings-cached#67]
use mysql2 0.4.0 sidekiq can't start, switch mysql 0.3.20 no problem.

```
(called from <class:CachedSettings> at /data/spole/www/shared/bundle/ruby/2.2.0/gems/rails-settings-cached-0.4.2/lib/rails-settings/cached_settings.rb:8)
/data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:50:in `establish_connection'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/railtie.rb:120:in `block (2 levels) in <class:Railtie>'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:27:in `each'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /data/spole/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
        from /data/spole/www/releases/16/config/environment.rb:5:in `<top (required)>'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
        from /data/spole/www/shared/bundle/ruby/2.2.0/gems/sidekiq-3.5.0/lib/sidekiq/cli.rb:247:in `boot_system'
        from /data/spole/www/shared/bundle/ruby/2.2.0/gems/sidekiq-3.5.0/lib/sidekiq/cli.rb:50:in `run'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/gems/sidekiq-3.5.0/bin/sidekiq:13:in `<top (required)>'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/bin/sidekiq:23:in `load'
        from /data/spole/www/releases/16/vendor/bundle/ruby/2.2.0/bin/sidekiq:23:in `<main>'
```

**Comment by huacnlee** [comment]
> Add `gem 'mysql2'` to your Gemfile

Do you did that?
